import random as rnd
import numpy as np
from sentence_transformers import CrossEncoder

#have json/py-dict of quizbowl questions
#get question and answer, then run the answer for the question as a query through the model, and the input of the user as the passage.
#Check if it is correct via model prediction
#IF INCORRECT, SAVE FOR 20 QUESTIONS LATER AND PICK A RANDOM OTHER QUIZBOWL QUESTION

class Questions:
    def __init__(self, questions_amount):
        self.question_amount = questions_amount
    def get_question(self):

        history_questions = {
            # --- US State Capitals (1–50) ---
            "1. What is the capital of Alabama?": "Montgomery",
            "2. What is the capital of Alaska?": "Juneau",
            "3. What is the capital of Arizona?": "Phoenix",
            "4. What is the capital of Arkansas?": "Little Rock",
            "5. What is the capital of California?": "Sacramento",
            "6. What is the capital of Colorado?": "Denver",
            "7. What is the capital of Connecticut?": "Hartford",
            "8. What is the capital of Delaware?": "Dover",
            "9. What is the capital of Florida?": "Tallahassee",
            "10. What is the capital of Georgia?": "Atlanta",
            "11. What is the capital of Hawaii?": "Honolulu",
            "12. What is the capital of Idaho?": "Boise",
            "13. What is the capital of Illinois?": "Springfield",
            "14. What is the capital of Indiana?": "Indianapolis",
            "15. What is the capital of Iowa?": "Des Moines",
            "16. What is the capital of Kansas?": "Topeka",
            "17. What is the capital of Kentucky?": "Frankfort",
            "18. What is the capital of Louisiana?": "Baton Rouge",
            "19. What is the capital of Maine?": "Augusta",
            "20. What is the capital of Maryland?": "Annapolis",
            "21. What is the capital of Massachusetts?": "Boston",
            "22. What is the capital of Michigan?": "Lansing",
            "23. What is the capital of Minnesota?": "Saint Paul",
            "24. What is the capital of Mississippi?": "Jackson",
            "25. What is the capital of Missouri?": "Jefferson City",
            "26. What is the capital of Montana?": "Helena",
            "27. What is the capital of Nebraska?": "Lincoln",
            "28. What is the capital of Nevada?": "Carson City",
            "29. What is the capital of New Hampshire?": "Concord",
            "30. What is the capital of New Jersey?": "Trenton",
            "31. What is the capital of New Mexico?": "Santa Fe",
            "32. What is the capital of New York?": "Albany",
            "33. What is the capital of North Carolina?": "Raleigh",
            "34. What is the capital of North Dakota?": "Bismarck",
            "35. What is the capital of Ohio?": "Columbus",
            "36. What is the capital of Oklahoma?": "Oklahoma City",
            "37. What is the capital of Oregon?": "Salem",
            "38. What is the capital of Pennsylvania?": "Harrisburg",
            "39. What is the capital of Rhode Island?": "Providence",
            "40. What is the capital of South Carolina?": "Columbia",
            "41. What is the capital of South Dakota?": "Pierre",
            "42. What is the capital of Tennessee?": "Nashville",
            "43. What is the capital of Texas?": "Austin",
            "44. What is the capital of Utah?": "Salt Lake City",
            "45. What is the capital of Vermont?": "Montpelier",
            "46. What is the capital of Virginia?": "Richmond",
            "47. What is the capital of Washington?": "Olympia",
            "48. What is the capital of West Virginia?": "Charleston",
            "49. What is the capital of Wisconsin?": "Madison",
            "50. What is the capital of Wyoming?": "Cheyenne",

            # --- World Capitals & Countries (51–100) ---
            "51. What is the capital of Canada?": "Ottawa",
            "52. What is the capital of Mexico?": "Mexico City",
            "53. What is the capital of Brazil?": "Brasília",
            "54. What is the capital of Argentina?": "Buenos Aires",
            "55. What is the capital of the United Kingdom?": "London",
            "56. What is the capital of France?": "Paris",
            "57. What is the capital of Germany?": "Berlin",
            "58. What is the capital of Italy?": "Rome",
            "59. What is the capital of Spain?": "Madrid",
            "60. What is the capital of Portugal?": "Lisbon",
            "61. What is the capital of Russia?": "Moscow",
            "62. What is the capital of China?": "Beijing",
            "63. What is the capital of Japan?": "Tokyo",
            "64. What is the capital of India?": "New Delhi",
            "65. What is the capital of South Korea?": "Seoul",
            "66. What is the capital of North Korea?": "Pyongyang",
            "67. What is the capital of Australia?": "Canberra",
            "68. What is the capital of New Zealand?": "Wellington",
            "69. What is the capital of Egypt?": "Cairo",
            "70. What is the capital of South Africa?": "Pretoria",
            "71. What is the capital of Kenya?": "Nairobi",
            "72. What is the capital of Nigeria?": "Abuja",
            "73. What is the capital of Turkey?": "Ankara",
            "74. What is the capital of Greece?": "Athens",
            "75. What is the capital of Sweden?": "Stockholm",
            "76. What is the capital of Norway?": "Oslo",
            "77. What is the capital of Finland?": "Helsinki",
            "78. What is the capital of Poland?": "Warsaw",
            "79. What is the capital of Ukraine?": "Kyiv",
            "80. What is the capital of Saudi Arabia?": "Riyadh",
            "81. What is the capital of Iran?": "Tehran",
            "82. What is the capital of Iraq?": "Baghdad",
            "83. What is the capital of Israel?": "Jerusalem",
            "84. What is the capital of Indonesia?": "Jakarta",
            "85. What is the capital of Thailand?": "Bangkok",
            "86. What is the capital of Vietnam?": "Hanoi",
            "87. What is the capital of the Philippines?": "Manila",
            "88. What is the capital of Malaysia?": "Kuala Lumpur",
            "89. What is the capital of Pakistan?": "Islamabad",
            "90. What is the capital of Bangladesh?": "Dhaka",
            "91. What is the capital of Chile?": "Santiago",
            "92. What is the capital of Peru?": "Lima",
            "93. What is the capital of Colombia?": "Bogotá",
            "94. What is the capital of Venezuela?": "Caracas",
            "95. What is the capital of Cuba?": "Havana",
            "96. What is the capital of Haiti?": "Port-au-Prince",
            "97. What is the capital of the Dominican Republic?": "Santo Domingo",
            "98. What is the capital of Switzerland?": "Bern",
            "99. What is the capital of Austria?": "Vienna",
            "100. What is the capital of Belgium?": "Brussels",

            # --- Geography, Wars, Historical Figures (101–200) ---
            "101. What river is the longest in the world?": "Nile River",
            "102. What mountain range separates Europe and Asia?": "Ural Mountains",
            "103. What desert is the largest hot desert in the world?": "Sahara Desert",
            "104. What ocean is the largest?": "Pacific Ocean",
            "105. What sea separates Europe and Africa?": "Mediterranean Sea",
            "106. Who was the first President of the United States?": "George Washington",
            "107. Who was the leader of Nazi Germany during World War II?": "Adolf Hitler",
            "108. Who was the British Prime Minister during most of World War II?": "Winston Churchill",
            "109. Who was the Soviet leader during World War II?": "Joseph Stalin",
            "110. Who was the Emperor of France defeated at Waterloo?": "Napoleon Bonaparte",
            "111. What war was fought between the North and South regions of the United States from 1861–1865?": "American Civil War",
            "112. What war was triggered by the assassination of Archduke Franz Ferdinand?": "World War I",
            "113. What conflict was fought between the United States and Vietnam in the 1960s–70s?": "Vietnam War",
            "114. What war was fought between Britain and its American colonies from 1775–1783?": "American Revolutionary War",
            "115. What canal connects the Atlantic and Pacific Oceans in Central America?": "Panama Canal",
            "116. What strait separates Alaska and Russia?": "Bering Strait",
            "117. What is the tallest mountain in Africa?": "Mount Kilimanjaro",
            "118. What is the capital of the European Union?": "Brussels",
            "119. What river runs through Baghdad?": "Tigris River",
            "120. What river runs through Egypt and empties into the Mediterranean?": "Nile River",
            "121. Who was the first Emperor of Rome?": "Augustus",
            "122. Who led the Mongol Empire at its height?": "Genghis Khan",
            "123. Who was the first female Prime Minister of the United Kingdom?": "Margaret Thatcher",
            "124. What wall fell in 1989 symbolizing the end of the Cold War?": "Berlin Wall",
            "125. What country was formerly known as Persia?": "Iran",
            "126. What country was formerly known as Siam?": "Thailand",
            "127. What country was formerly known as Ceylon?": "Sri Lanka",
            "128. What is the largest island in the world?": "Greenland",
            "129. What is the smallest country in the world?": "Vatican City",
            "130. What river flows through Paris?": "Seine River",
            "131. What river flows through London?": "Thames River",
            "132. What empire was ruled by Suleiman the Magnificent?": "Ottoman Empire",
            "133. What empire built Machu Picchu?": "Inca Empire",
            "134. What civilization built the pyramids at Giza?": "Ancient Egyptians",
            "135. What was the name of the trade route connecting China to Europe?": "Silk Road",
            "136. Who discovered the sea route to India around Africa in 1498?": "Vasco da Gama",
            "137. Who completed the first circumnavigation of the globe?": "Ferdinand Magellan",
            "138. What battle marked the end of Napoleon’s rule in 1815?": "Battle of Waterloo",
            "139. What battle was a turning point in the American Civil War in 1863?": "Battle of Gettysburg",
            "140. What agreement ended World War I?": "Treaty of Versailles",
            "141. What organization was formed after World War II to promote peace?": "United Nations",
            "142. What is the capital of the United Arab Emirates?": "Abu Dhabi",
            "143. What country controls the island of Corsica?": "France",
            "144. What country controls Greenland?": "Denmark",
            "145. What mountain range runs along the west coast of South America?": "Andes Mountains",
            "146. What plateau is often called the 'Roof of the World'?": "Tibetan Plateau",
            "147. What is the longest river in South America?": "Amazon River",
            "148. What is the largest country by land area?": "Russia",
            "149. What line divides North and South Korea?": "38th Parallel",
            "150. What city was divided by a wall from 1961 to 1989?": "Berlin",
            "151. Who was the first President of South Africa after apartheid?": "Nelson Mandela",
            "152. Who was assassinated in Dallas in 1963?": "John F. Kennedy",
            "153. What country did the United States purchase Alaska from?": "Russia",
            "154. What is the capital of Qatar?": "Doha",
            "155. What is the capital of Afghanistan?": "Kabul",
            "156. What is the capital of Syria?": "Damascus",
            "157. What is the capital of Lebanon?": "Beirut",
            "158. What is the capital of Jordan?": "Amman",
            "159. What is the capital of Hungary?": "Budapest",
            "160. What is the capital of the Czech Republic?": "Prague",
            "161. What is the capital of Slovakia?": "Bratislava",
            "162. What is the capital of Romania?": "Bucharest",
            "163. What is the capital of Bulgaria?": "Sofia",
            "164. What is the capital of Croatia?": "Zagreb",
            "165. What is the capital of Serbia?": "Belgrade",
            "166. What is the capital of Slovenia?": "Ljubljana",
            "167. What is the capital of Morocco?": "Rabat",
            "168. What is the capital of Algeria?": "Algiers",
            "169. What is the capital of Tunisia?": "Tunis",
            "170. What is the capital of Libya?": "Tripoli",
            "171. What is the capital of Sudan?": "Khartoum",
            "172. What is the capital of Ethiopia?": "Addis Ababa",
            "173. What is the capital of Tanzania?": "Dodoma",
            "174. What is the capital of Uganda?": "Kampala",
            "175. What is the capital of Zimbabwe?": "Harare",
            "176. What is the capital of Zambia?": "Lusaka",
            "177. What is the capital of Angola?": "Luanda",
            "178. What is the capital of Ghana?": "Accra",
            "179. What is the capital of Ivory Coast?": "Yamoussoukro",
            "180. What is the capital of Senegal?": "Dakar",
            "181. What is the capital of Cambodia?": "Phnom Penh",
            "182. What is the capital of Laos?": "Vientiane",
            "183. What is the capital of Myanmar?": "Naypyidaw",
            "184. What is the capital of Nepal?": "Kathmandu",
            "185. What is the capital of Sri Lanka?": "Sri Jayawardenepura Kotte",
            "186. What is the capital of Mongolia?": "Ulaanbaatar",
            "187. What is the capital of Kazakhstan?": "Astana",
            "188. What is the capital of Uzbekistan?": "Tashkent",
            "189. What is the capital of Turkmenistan?": "Ashgabat",
            "190. What is the capital of Kyrgyzstan?": "Bishkek",
            "191. What is the capital of Tajikistan?": "Dushanbe",
            "192. What is the capital of Bolivia?": "Sucre",
            "193. What is the capital of Paraguay?": "Asunción",
            "194. What is the capital of Uruguay?": "Montevideo",
            "195. What is the capital of Ecuador?": "Quito",
            "196. What is the capital of Guatemala?": "Guatemala City",
            "197. What is the capital of Honduras?": "Tegucigalpa",
            "198. What is the capital of Costa Rica?": "San José",
            "199. What is the capital of Panama?": "Panama City",
            "200. What is the capital of Iceland?": "Reykjavík",
        }
        science_quizbowl_questions = {
            # --- Astronomy (1–50) ---
            "1. What is the closest planet to the Sun?": "Mercury",
            "2. What planet is known as the Red Planet?": "Mars",
            "3. What is the largest planet in our solar system?": "Jupiter",
            "4. What galaxy contains our Solar System?": "Milky Way",
            "5. What is the name of Earth's natural satellite?": "Moon",
            "6. What force keeps planets in orbit around the Sun?": "Gravity",
            "7. What is the hottest planet in the solar system?": "Venus",
            "8. What is the name of the first artificial Earth satellite?": "Sputnik 1",
            "9. Who was the first person to walk on the Moon?": "Neil Armstrong",
            "10. What is the term for a star that suddenly increases in brightness?": "Supernova",
            "11. What is the boundary around a black hole beyond which nothing escapes?": "Event horizon",
            "12. What planet has the most prominent ring system?": "Saturn",
            "13. What is the name of the telescope launched in 1990 that orbits Earth?": "Hubble Space Telescope",
            "14. What is the unit used to measure distances between stars?": "Light-year",
            "15. What planet is known for its Great Red Spot?": "Jupiter",
            "16. What is the name of our Sun’s galaxy cluster?": "Local Group",
            "17. What is the smallest planet in the solar system?": "Mercury",
            "18. What phenomenon causes the Northern Lights?": "Aurora Borealis",
            "19. What spacecraft first landed humans on the Moon?": "Apollo 11",
            "20. What is the term for a rocky object that enters Earth's atmosphere and burns up?": "Meteor",
            "21. What is the name of the nearest star to Earth after the Sun?": "Proxima Centauri",
            "22. What planet is tilted on its side?": "Uranus",
            "23. What is the term for the apparent path of the Sun across the sky?": "Ecliptic",
            "24. What is the name of the first woman in space?": "Valentina Tereshkova",
            "25. What planet has the longest day relative to its year?": "Venus",
            "26. What is the name of the largest asteroid in the asteroid belt?": "Ceres",
            "27. What is the term for a system of millions or billions of stars?": "Galaxy",
            "28. What is the name of the first reusable spacecraft?": "Space Shuttle",
            "29. What is the name of the dwarf planet discovered in 1930?": "Pluto",
            "30. What is the Kuiper Belt located beyond?": "Neptune",
            "31. What is the name of the first exoplanet discovered orbiting a Sun-like star?": "51 Pegasi b",
            "32. What type of galaxy is the Milky Way?": "Spiral galaxy",
            "33. What is the name of the brightest star in the night sky?": "Sirius",
            "34. What is the escape velocity of Earth approximately (km/s)?": "11.2",
            "35. What planet has the strongest magnetic field?": "Jupiter",
            "36. What is the term for the bending of light by gravity?": "Gravitational lensing",
            "37. What is the name of NASA’s Mars rover that landed in 2021?": "Perseverance",
            "38. What is the Chandrasekhar limit related to?": "White dwarf mass limit",
            "39. What is the name of the supermassive black hole at the center of the Milky Way?": "Sagittarius A*",
            "40. What is the main element in the Sun?": "Hydrogen",
            "41. What is the name of the first privately developed spacecraft to reach orbit?": "Falcon 1",
            "42. What planet is known as the Morning Star?": "Venus",
            "43. What is the term for a planet outside our solar system?": "Exoplanet",
            "44. What law describes the relationship between a planet’s orbital period and its distance from the Sun?": "Kepler’s Third Law",
            "45. What space telescope succeeded Hubble in 2021?": "James Webb Space Telescope",
            "46. What is the name of the boundary of the Sun’s influence in space?": "Heliopause",
            "47. What phenomenon causes a solar eclipse?": "Moon blocking the Sun",
            "48. What is the name of the first American astronaut in space?": "Alan Shepard",
            "49. What is the largest moon of Saturn?": "Titan",
            "50. What is the cosmic microwave background radiation a remnant of?": "Big Bang",

            # --- Biology (51–100) ---
            "51. What is the basic unit of life?": "Cell",
            "52. What organelle is known as the powerhouse of the cell?": "Mitochondria",
            "53. What molecule carries genetic information?": "DNA",
            "54. Who proposed the theory of evolution by natural selection?": "Charles Darwin",
            "55. What process do plants use to make food?": "Photosynthesis",
            "56. What blood cells carry oxygen?": "Red blood cells",
            "57. What kingdom do mushrooms belong to?": "Fungi",
            "58. What is the largest organ in the human body?": "Skin",
            "59. What type of bond holds the two strands of DNA together?": "Hydrogen bonds",
            "60. What is the study of heredity called?": "Genetics",
            "61. What is the name of the protein that carries oxygen in blood?": "Hemoglobin",
            "62. What is the function of ribosomes?": "Protein synthesis",
            "63. What is the term for programmed cell death?": "Apoptosis",
            "64. What gas do plants absorb during photosynthesis?": "Carbon dioxide",
            "65. What is the largest bone in the human body?": "Femur",
            "66. What scientist discovered penicillin?": "Alexander Fleming",
            "67. What is the process by which cells divide to form two identical cells?": "Mitosis",
            "68. What is the process by which gametes are formed?": "Meiosis",
            "69. What part of the brain controls balance?": "Cerebellum",
            "70. What is the name of the double helix model’s co-discoverer with Watson?": "Francis Crick",
            "71. What is the universal energy currency of the cell?": "ATP",
            "72. What type of organism makes its own food?": "Autotroph",
            "73. What is the largest phylum in the animal kingdom?": "Arthropoda",
            "74. What is the name of the process by which bacteria exchange genetic material?": "Conjugation",
            "75. What is the study of ecosystems called?": "Ecology",
            "76. What is the primary function of white blood cells?": "Fight infection",
            "77. What pigment gives plants their green color?": "Chlorophyll",
            "78. What is the term for organisms that can live in extreme environments?": "Extremophiles",
            "79. What scientist is known as the father of modern taxonomy?": "Carl Linnaeus",
            "80. What is the longest phase of the cell cycle?": "Interphase",
            "81. What structure regulates what enters and leaves the cell?": "Cell membrane",
            "82. What is the name of the largest artery in the human body?": "Aorta",
            "83. What is the process of converting RNA into protein called?": "Translation",
            "84. What is the term for a trait that masks another trait?": "Dominant",
            "85. What is the term for animals that maintain constant body temperature?": "Endotherms",
            "86. What organ filters blood to produce urine?": "Kidney",
            "87. What is the name of the theory that cells come from preexisting cells?": "Cell theory",
            "88. What is the main structural component of plant cell walls?": "Cellulose",
            "89. What is the smallest unit of classification in taxonomy?": "Species",
            "90. What is the study of viruses called?": "Virology",
            "91. What structure in plants transports water?": "Xylem",
            "92. What structure transports sugars in plants?": "Phloem",
            "93. What is the name of the scientist who discovered blood circulation?": "William Harvey",
            "94. What is the term for a symbiotic relationship where both benefit?": "Mutualism",
            "95. What is the scientific name for humans?": "Homo sapiens",
            "96. What is the name of the sugar found in DNA?": "Deoxyribose",
            "97. What is the name of the first cloned mammal?": "Dolly",
            "98. What organ produces insulin?": "Pancreas",
            "99. What is the name of the largest part of the human brain?": "Cerebrum",
            "100. What is the process by which organisms maintain stable internal conditions?": "Homeostasis",

            # --- Earth Science & Historical Science (101–150) ---
            "101. What is the outermost layer of Earth called?": "Crust",
            "102. What scale measures earthquake magnitude?": "Richter scale",
            "103. What is the theory that continents move over time?": "Plate tectonics",
            "104. Who proposed the theory of continental drift?": "Alfred Wegener",
            "105. What is molten rock beneath Earth’s surface called?": "Magma",
            "106. What is the process by which rocks are broken down?": "Weathering",
            "107. What is the most abundant gas in Earth's atmosphere?": "Nitrogen",
            "108. What instrument measures atmospheric pressure?": "Barometer",
            "109. What is the boundary between tectonic plates called?": "Fault",
            "110. What is the name of the supercontinent that existed 300 million years ago?": "Pangaea",
            "111. What layer of Earth is liquid and generates the magnetic field?": "Outer core",
            "112. What phenomenon is caused by the tilt of Earth's axis?": "Seasons",
            "113. What is the water cycle process where water vapor becomes liquid?": "Condensation",
            "114. What is the study of fossils called?": "Paleontology",
            "115. What is the largest ocean on Earth?": "Pacific Ocean",
            "116. What is the name of the boundary where two plates collide?": "Convergent boundary",
            "117. What is the name of the scale that measures tornado intensity?": "Fujita scale",
            "118. What mineral is the hardest natural substance?": "Diamond",
            "119. What is the main greenhouse gas emitted by human activities?": "Carbon dioxide",
            "120. What is the name of the process that forms sedimentary rock?": "Compaction and cementation",
            "121. Who formulated the laws of motion?": "Isaac Newton",
            "122. Who developed the theory of relativity?": "Albert Einstein",
            "123. Who discovered radioactivity?": "Henri Becquerel",
            "124. Who discovered the electron?": "J.J. Thomson",
            "125. Who discovered the nucleus of the atom?": "Ernest Rutherford",
            "126. Who developed the periodic table?": "Dmitri Mendeleev",
            "127. What scientist discovered X-rays?": "Wilhelm Röntgen",
            "128. Who discovered the structure of DNA with Watson and Crick?": "Rosalind Franklin",
            "129. What scientist is known for the uncertainty principle?": "Werner Heisenberg",
            "130. Who proposed the heliocentric model of the solar system?": "Nicolaus Copernicus",
            "131. Who improved the telescope and supported heliocentrism?": "Galileo Galilei",
            "132. Who discovered gravity after observing a falling apple?": "Isaac Newton",
            "133. Who developed the three laws of planetary motion?": "Johannes Kepler",
            "134. Who discovered oxygen independently in 1774?": "Joseph Priestley",
            "135. Who is known as the father of modern chemistry?": "Antoine Lavoisier",
            "136. Who discovered the neutron?": "James Chadwick",
            "137. Who proposed the Big Bang theory?": "Georges Lemaître",
            "138. Who discovered the planet Uranus?": "William Herschel",
            "139. Who was the first American woman in space?": "Sally Ride",
            "140. What mission first landed humans on the Moon?": "Apollo 11",
            "141. What particle carries a negative electric charge?": "Electron",
            "142. What is the chemical symbol for gold?": "Au",
            "143. What is the speed of light in vacuum (m/s)?": "299792458",
            "144. What is the name of the process by which energy is released from the nucleus?": "Nuclear fission",
            "145. What is the name of the force that opposes motion between surfaces?": "Friction",
            "146. What is the unit of electric current?": "Ampere",
            "147. What is the name of the first law of thermodynamics also known as?": "Law of conservation of energy",
            "148. What is the main component of natural gas?": "Methane",
            "149. What element has atomic number 1?": "Hydrogen",
            "150. What is the study of earthquakes called?": "Seismology"
        }
        english_quizbowl_questions = {
            # --- Grammar & Parts of Speech (1–40) ---
            "1. What part of speech describes a noun?": "Adjective",
            "2. What part of speech modifies a verb?": "Adverb",
            "3. What is a word that replaces a noun called?": "Pronoun",
            "4. What is a group of words with a subject and predicate called?": "Clause",
            "5. What is a word that connects clauses or sentences called?": "Conjunction",
            "6. What type of sentence makes a statement?": "Declarative sentence",
            "7. What type of sentence asks a question?": "Interrogative sentence",
            "8. What type of sentence gives a command?": "Imperative sentence",
            "9. What type of sentence expresses strong emotion?": "Exclamatory sentence",
            "10. What is the term for a word that imitates a sound?": "Onomatopoeia",
            "11. What is a comparison using 'like' or 'as' called?": "Simile",
            "12. What is a direct comparison without using 'like' or 'as'?": "Metaphor",
            "13. What is giving human traits to nonhuman things called?": "Personification",
            "14. What is the repetition of initial consonant sounds called?": "Alliteration",
            "15. What is the main idea of a paragraph called?": "Topic sentence",
            "16. What is the term for a word opposite in meaning to another word?": "Antonym",
            "17. What is a word similar in meaning to another word called?": "Synonym",
            "18. What is a sentence fragment missing?": "Subject or predicate",
            "19. What punctuation mark ends a question?": "Question mark",
            "20. What is a run-on sentence?": "Two or more independent clauses joined without proper punctuation",
            "21. What is the name for a noun that names a specific person or place?": "Proper noun",
            "22. What is a verb that links the subject to a description called?": "Linking verb",
            "23. What is the base form of a verb called?": "Infinitive",
            "24. What is the -ing form of a verb functioning as a noun called?": "Gerund",
            "25. What is the name of a verb form used as an adjective?": "Participle",
            "26. What is a group of words without a subject-verb pair called?": "Phrase",
            "27. What is a noun formed from a verb called?": "Gerund",
            "28. What is the term for words added to the beginning of a word?": "Prefix",
            "29. What is the term for words added to the end of a word?": "Suffix",
            "30. What is the root of a word called?": "Root word",
            "31. What is a word formed from the initial letters of other words?": "Acronym",
            "32. What is the repetition of vowel sounds called?": "Assonance",
            "33. What is the repetition of consonant sounds within words called?": "Consonance",
            "34. What is incorrect grammar usage called?": "Solecism",
            "35. What is the name for a word that is spelled the same but has different meanings?": "Homonym",
            "36. What is the term for a word that sounds the same but is spelled differently?": "Homophone",
            "37. What is a group of lines in a poem called?": "Stanza",
            "38. What is the pattern of rhyme in a poem called?": "Rhyme scheme",
            "39. What is unrhymed iambic pentameter called?": "Blank verse",
            "40. What is the stressed-unstressed syllable pattern called?": "Meter",

            # --- Literary Terms & Devices (41–80) ---
            "41. What is the central message of a story called?": "Theme",
            "42. What is the turning point of a story called?": "Climax",
            "43. What is the introduction of a story called?": "Exposition",
            "44. What is the sequence of events in a story called?": "Plot",
            "45. What is the struggle between opposing forces called?": "Conflict",
            "46. What is a narrator outside the story called?": "Third-person narrator",
            "47. What is narration using 'I' called?": "First-person point of view",
            "48. What is a story meant to teach a moral lesson called?": "Fable",
            "49. What is a long narrative poem about heroic deeds called?": "Epic",
            "50. What is a brief reference to another work called?": "Allusion",
            "51. What is exaggeration for effect called?": "Hyperbole",
            "52. What is a contradiction in terms called?": "Oxymoron",
            "53. What is a statement that means the opposite of what it says called?": "Irony",
            "54. What is a play on words called?": "Pun",
            "55. What is a tragic flaw in a hero called?": "Hamartia",
            "56. What is a story that uses symbolic figures to convey truth called?": "Allegory",
            "57. What is the emotional atmosphere of a story called?": "Mood",
            "58. What is the author’s attitude toward the subject called?": "Tone",
            "59. What is a 14-line poem called?": "Sonnet",
            "60. What is a five-line humorous poem called?": "Limerick",
            "61. What is a comparison between unlike things to clarify meaning called?": "Analogy",
            "62. What is the repetition of words at the beginning of clauses called?": "Anaphora",
            "63. What is the perspective of the narrator called?": "Point of view",
            "64. What is a character who opposes the protagonist called?": "Antagonist",
            "65. What is the main character called?": "Protagonist",
            "66. What is a speech by one character alone on stage called?": "Soliloquy",
            "67. What is a poem mourning the dead called?": "Elegy",
            "68. What is a humorous poem about rural life called?": "Pastoral",
            "69. What is a brief witty saying called?": "Epigram",
            "70. What is the repetition of the same word at the end of clauses called?": "Epistrophe",
            "71. What is a narrative that begins in the middle of events called?": "In medias res",
            "72. What is a struggle within a character called?": "Internal conflict",
            "73. What is a struggle between characters called?": "External conflict",
            "74. What is a work that makes fun of human weakness called?": "Satire",
            "75. What is a pair of rhyming lines called?": "Couplet",
            "76. What is a story passed down orally called?": "Folktale",
            "77. What is a traditional story explaining natural phenomena called?": "Myth",
            "78. What is a story based on historical events but fictionalized called?": "Historical fiction",
            "79. What is a narrative poem telling a dramatic story called?": "Ballad",
            "80. What is a poem praising someone or something called?": "Ode",

            # --- Authors & Works (81–120) ---
            "81. Who wrote 'Romeo and Juliet'?": "William Shakespeare",
            "82. Who wrote 'Pride and Prejudice'?": "Jane Austen",
            "83. Who wrote 'Moby-Dick'?": "Herman Melville",
            "84. Who wrote '1984'?": "George Orwell",
            "85. Who wrote 'The Great Gatsby'?": "F. Scott Fitzgerald",
            "86. Who wrote 'To Kill a Mockingbird'?": "Harper Lee",
            "87. Who wrote 'The Odyssey'?": "Homer",
            "88. Who wrote 'The Iliad'?": "Homer",
            "89. Who wrote 'The Catcher in the Rye'?": "J.D. Salinger",
            "90. Who wrote 'The Hobbit'?": "J.R.R. Tolkien",
            "91. Who wrote 'Brave New World'?": "Aldous Huxley",
            "92. Who wrote 'The Scarlet Letter'?": "Nathaniel Hawthorne",
            "93. Who wrote 'Jane Eyre'?": "Charlotte Brontë",
            "94. Who wrote 'Wuthering Heights'?": "Emily Brontë",
            "95. Who wrote 'The Adventures of Huckleberry Finn'?": "Mark Twain",
            "96. Who wrote 'The Divine Comedy'?": "Dante Alighieri",
            "97. Who wrote 'Paradise Lost'?": "John Milton",
            "98. Who wrote 'Animal Farm'?": "George Orwell",
            "99. Who wrote 'The Lord of the Rings'?": "J.R.R. Tolkien",
            "100. Who wrote 'The Grapes of Wrath'?": "John Steinbeck",
            "101. Who wrote 'Fahrenheit 451'?": "Ray Bradbury",
            "102. Who wrote 'Crime and Punishment'?": "Fyodor Dostoevsky",
            "103. Who wrote 'War and Peace'?": "Leo Tolstoy",
            "104. Who wrote 'The Brothers Karamazov'?": "Fyodor Dostoevsky",
            "105. Who wrote 'The Old Man and the Sea'?": "Ernest Hemingway",
            "106. Who wrote 'The Canterbury Tales'?": "Geoffrey Chaucer",
            "107. Who wrote 'Macbeth'?": "William Shakespeare",
            "108. Who wrote 'Hamlet'?": "William Shakespeare",
            "109. Who wrote 'The Picture of Dorian Gray'?": "Oscar Wilde",
            "110. Who wrote 'The Alchemist'?": "Paulo Coelho",
            "111. Who wrote 'The Chronicles of Narnia'?": "C.S. Lewis",
            "112. Who wrote 'Les Misérables'?": "Victor Hugo",
            "113. Who wrote 'Dracula'?": "Bram Stoker",
            "114. Who wrote 'Frankenstein'?": "Mary Shelley",
            "115. Who wrote 'The Kite Runner'?": "Khaled Hosseini",
            "116. Who wrote 'The Hunger Games'?": "Suzanne Collins",
            "117. Who wrote 'The Fault in Our Stars'?": "John Green",
            "118. Who wrote 'Of Mice and Men'?": "John Steinbeck",
            "119. Who wrote 'A Tale of Two Cities'?": "Charles Dickens",
            "120. Who wrote 'Don Quixote'?": "Miguel de Cervantes"
        }
        math_quizbowl_questions = {
            # --- Algebra (1–30) ---
            "1. What is the value of x in the equation 3x + 5 = 20?": "5",
            "2. Solve for x: 2x - 7 = 13.": "10",
            "3. What is the slope of the line y = 4x + 1?": "4",
            "4. What is the y-intercept of y = -2x + 6?": "6",
            "5. What is the solution to the system: x + y = 10 and x - y = 2?": "x = 6, y = 4",
            "6. What is 5 squared?": "25",
            "7. What is the square root of 169?": "13",
            "8. Factor: x^2 - 9.": "(x - 3)(x + 3)",
            "9. Expand: (x + 4)(x + 2).": "x^2 + 6x + 8",
            "10. Solve: x^2 = 49.": "x = 7 or x = -7",
            "11. What is the quadratic formula?": "(-b ± √(b^2 - 4ac)) / (2a)",
            "12. What is the value of 2^5?": "32",
            "13. Simplify: 3x + 4x.": "7x",
            "14. Solve: 4(x - 2) = 20.": "7",
            "15. What is the slope between points (1,2) and (3,6)?": "2",
            "16. Simplify: (2x^3)(3x^2).": "6x^5",
            "17. What is the vertex form of a quadratic equation?": "y = a(x - h)^2 + k",
            "18. Solve: 9x = 81.": "9",
            "19. What is 10% of 250?": "25",
            "20. Simplify: (x^4)/(x^2).": "x^2",
            "21. Solve: |x| = 6.": "x = 6 or x = -6",
            "22. What is the midpoint between (2,4) and (6,8)?": "(4,6)",
            "23. Convert 0.75 to a fraction.": "3/4",
            "24. What is the slope-intercept form of a linear equation?": "y = mx + b",
            "25. Evaluate: 3^3.": "27",
            "26. What is the value of x if x/4 = 5?": "20",
            "27. Solve: x^2 - 16 = 0.": "x = 4 or x = -4",
            "28. Simplify: 5(2x + 3).": "10x + 15",
            "29. What is the distance formula?": "√((x2 - x1)^2 + (y2 - y1)^2)",
            "30. What is the discriminant of ax^2 + bx + c?": "b^2 - 4ac",

            # --- Geometry (31–60) ---
            "31. What is the area formula for a triangle?": "1/2 * base * height",
            "32. What is the Pythagorean theorem?": "a^2 + b^2 = c^2",
            "33. What is the circumference formula of a circle?": "2πr",
            "34. What is the area of a circle?": "πr^2",
            "35. How many degrees are in a triangle?": "180",
            "36. What is the volume formula of a rectangular prism?": "length × width × height",
            "37. What is the sum of interior angles of a quadrilateral?": "360",
            "38. What is the formula for the area of a rectangle?": "length × width",
            "39. What is the volume of a cylinder?": "πr^2h",
            "40. What is the slope of a horizontal line?": "0",
            "41. What is the slope of a vertical line?": "Undefined",
            "42. What is the area of a trapezoid?": "1/2 * (b1 + b2) * h",
            "43. What is the measure of each angle in an equilateral triangle?": "60",
            "44. What is the distance around a polygon called?": "Perimeter",
            "45. What is the formula for the volume of a sphere?": "4/3 πr^3",
            "46. What is the formula for the surface area of a sphere?": "4πr^2",
            "47. What is complementary angles?": "Two angles that sum to 90 degrees",
            "48. What is supplementary angles?": "Two angles that sum to 180 degrees",
            "49. What is the area of a parallelogram?": "base × height",
            "50. What is the hypotenuse in a right triangle?": "The side opposite the right angle",
            "51. What is the interior angle sum formula for an n-sided polygon?": "(n - 2) × 180",
            "52. What is the volume of a cone?": "1/3 πr^2h",
            "53. What is a 90-degree angle called?": "Right angle",
            "54. What is a 180-degree angle called?": "Straight angle",
            "55. What is a polygon with 8 sides called?": "Octagon",
            "56. What is the diagonal of a square with side length s?": "s√2",
            "57. What is the area of a square?": "side^2",
            "58. What is the relationship between radius and diameter?": "Diameter = 2 × radius",
            "59. What is a triangle with all unequal sides called?": "Scalene triangle",
            "60. What is a triangle with two equal sides called?": "Isosceles triangle",

            # --- Advanced/General Math (61–100) ---
            "61. What is the factorial of 5?": "120",
            "62. What is the probability of flipping heads on a fair coin?": "1/2",
            "63. What is the mean of 2, 4, 6, 8?": "5",
            "64. What is the median of 1, 3, 5, 7, 9?": "5",
            "65. What is the mode of 2, 2, 3, 4?": "2",
            "66. What is 7! ?": "5040",
            "67. What is the derivative of x^2?": "2x",
            "68. What is the derivative of 3x?": "3",
            "69. What is the integral of 2x?": "x^2 + C",
            "70. What is the value of π approximately?": "3.14",
            "71. What is the solution to 2^x = 8?": "3",
            "72. What is the square root of 225?": "15",
            "73. What is the slope of y = -3x + 2?": "-3",
            "74. What is the area of a circle with radius 3?": "9π",
            "75. What is the volume of a cube with side length 4?": "64",
            "76. What is the domain of a function?": "All possible input values",
            "77. What is the range of a function?": "All possible output values",
            "78. What is a prime number?": "A number with exactly two positive factors",
            "79. What is the least common multiple of 4 and 6?": "12",
            "80. What is the greatest common factor of 12 and 18?": "6",
            "81. What is the sum of the first 10 positive integers?": "55",
            "82. What is the formula for simple interest?": "I = Prt",
            "83. What is the formula for compound interest?": "A = P(1 + r/n)^(nt)",
            "84. What is the value of log10(100)?": "2",
            "85. What is the solution to x^3 = 27?": "3",
            "86. What is the standard form of a quadratic equation?": "ax^2 + bx + c = 0",
            "87. What is the imaginary unit i equal to?": "√(-1)",
            "88. What is the absolute value of -15?": "15",
            "89. What is the sum of interior angles of a pentagon?": "540",
            "90. What is 0.2 as a fraction?": "1/5",
            "91. What is the formula for the area of a sector?": "1/2 r^2θ",
            "92. What is the cosine of 0 degrees?": "1",
            "93. What is the sine of 90 degrees?": "1",
            "94. What is the tangent of 45 degrees?": "1",
            "95. What is the formula for the arithmetic sequence nth term?": "a + (n - 1)d",
            "96. What is the formula for the geometric sequence nth term?": "a(r)^(n - 1)",
            "97. What is the solution to x - 12 = -5?": "7",
            "98. What is 25% of 80?": "20",
            "99. What is the value of 4^3?": "64",
            "100. What is the cube root of 64?": "4"
        }

        history_weight = 10
        science_weight = 10
        english_weight = 10
        math_weight = 10

        weights = [history_weight, science_weight,english_weight, math_weight]
        subjects = rnd.choices([history_questions, science_quizbowl_questions,english_quizbowl_questions,math_quizbowl_questions], weights=weights, k=self.question_amount)

        for subject in subjects:
            question, answer = rnd.choice(list(subject.items()))
        return question, answer




model = CrossEncoder("cross-encoder/ms-marco-MiniLM-L6-v2")
going = True
while going:
    Quizzer = Questions(1)
    question, answer = Quizzer.get_question()

    print(f"\n-------------------------------------------------------------\n"
          f"{question}                   "
          f"\n-------------------------------------------------------------\n")
    query = answer
    passages = input("-> ")



    if passages == "done":
        going = False
    scores = model.predict((query, passages))
    print(scores)
    print(answer)
